# Generated by Django 3.1.7 on 2022-09-29 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_norma',
            fields=[
                ('cod_tipo_norma', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_norma', models.CharField(max_length=40, verbose_name='Tipo Norma')),
                ('cod_cadastro', models.IntegerField(default=1, editable=False, verbose_name='Codigo Cadastro')),
                ('cod_modulo', models.IntegerField(default=15, editable=False, verbose_name='Codigo Modulo')),
                ('id', models.IntegerField(blank=True, editable=False, null=True, verbose_name='id')),
            ],
            options={
                'verbose_name': '002.Tipo Norma',
                'verbose_name_plural': '002. Tipo Normas',
                'db_table': 'cadastros"."tipo_norma',
                'ordering': None,
            },
        ),
        migrations.CreateModel(
            name='normas',
            fields=[
                ('cod_norma', models.AutoField(primary_key=True, serialize=False)),
                ('exercicio', models.CharField(default='2022', max_length=4, verbose_name='Exercicio')),
                ('nom_norma', models.CharField(max_length=80, verbose_name='Nome Norma')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('num_norma', models.CharField(max_length=30, verbose_name='Numero Norma')),
                ('dt_publicacao', models.DateField(default=datetime.datetime(2022, 9, 29, 11, 42, 0, 908197), null=True, verbose_name='Data Publicação')),
                ('dt_assinatura', models.DateField(default=datetime.datetime(2022, 9, 29, 11, 42, 0, 908197), null=True, verbose_name='Data Assinatura')),
                ('id', models.IntegerField(blank=True, editable=False, null=True, verbose_name='id')),
                ('cod_tipo_norma', models.ForeignKey(db_column='cod_tipo_norma', on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipo_norma')),
            ],
            options={
                'verbose_name': '003.Normas',
                'verbose_name_plural': '003.Normas',
                'db_table': 'cadastros"."norma',
                'ordering': None,
            },
        ),
    ]
