# Generated by Django 3.1.7 on 2022-09-30 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normas',
            name='dt_assinatura',
            field=models.DateField(default=datetime.datetime(2022, 9, 30, 10, 36, 4, 690825), null=True, verbose_name='Data Assinatura'),
        ),
        migrations.AlterField(
            model_name='normas',
            name='dt_publicacao',
            field=models.DateField(default=datetime.datetime(2022, 9, 30, 10, 36, 4, 690825), null=True, verbose_name='Data Publicação'),
        ),
    ]
