# Generated by Django 3.1.7 on 2022-09-30 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20220930_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normas',
            name='dt_assinatura',
            field=models.DateField(default=datetime.datetime(2022, 9, 30, 10, 56, 54, 754757), null=True, verbose_name='Data Assinatura'),
        ),
        migrations.AlterField(
            model_name='normas',
            name='dt_publicacao',
            field=models.DateField(default=datetime.datetime(2022, 9, 30, 10, 56, 54, 754757), null=True, verbose_name='Data Publicação'),
        ),
    ]
