# Generated by Django 3.2.22 on 2023-11-01 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20220930_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normas',
            name='dt_assinatura',
            field=models.DateField(default=datetime.datetime(2023, 11, 1, 13, 12, 28, 445246), null=True, verbose_name='Data Assinatura'),
        ),
        migrations.AlterField(
            model_name='normas',
            name='dt_publicacao',
            field=models.DateField(default=datetime.datetime(2023, 11, 1, 13, 12, 28, 445246), null=True, verbose_name='Data Publicação'),
        ),
        migrations.AlterField(
            model_name='normas',
            name='exercicio',
            field=models.CharField(default='2023', max_length=4, verbose_name='Exercicio'),
        ),
    ]
