# Generated by Django 3.2.22 on 2023-12-13 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20231101_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normas',
            name='dt_assinatura',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 8, 22, 51, 258819), null=True, verbose_name='Data Assinatura'),
        ),
        migrations.AlterField(
            model_name='normas',
            name='dt_publicacao',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 8, 22, 51, 258819), null=True, verbose_name='Data Publicação'),
        ),
    ]
