# Generated by Django 3.2.22 on 2023-12-13 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_auto_20231213_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normas',
            name='dt_assinatura',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 10, 29, 30, 799672), null=True, verbose_name='Data Assinatura'),
        ),
        migrations.AlterField(
            model_name='normas',
            name='dt_publicacao',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 10, 29, 30, 799672), null=True, verbose_name='Data Publicação'),
        ),
    ]
