# Generated by Django 3.2.22 on 2024-06-27 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_auto_20231213_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normas',
            name='dt_assinatura',
            field=models.DateField(default=datetime.datetime(2024, 6, 27, 7, 59, 56, 623363), null=True, verbose_name='Data Assinatura'),
        ),
        migrations.AlterField(
            model_name='normas',
            name='dt_publicacao',
            field=models.DateField(default=datetime.datetime(2024, 6, 27, 7, 59, 56, 623363), null=True, verbose_name='Data Publicação'),
        ),
        migrations.AlterField(
            model_name='normas',
            name='exercicio',
            field=models.CharField(default='2024', max_length=4, verbose_name='Exercicio'),
        ),
    ]
